import {
  AgentRoleProfile,
  PipelineStage,
  AgentLogStep,
  QATestResult,
  GitHubTrendingRepo,
} from '@/types';

// ==========================================
// 1. SQUAD AGENT ROSTER (13 AGENTS)
// ==========================================
export const SQUAD_AGENTS: AgentRoleProfile[] = [
  {
    id: 'agent_supreme_brainstorming',
    name: 'Supreme Brainstorming Leader',
    code: 'LEADER_BRAINSTORMING',
    category: 'LEADER',
    phase: 'Brainstorming & Flow Mapping',
    roleDescription: 'Tổng chỉ huy tối cao, phân rã mục tiêu, xuất sơ đồ luồng ý tưởng và phản biện đa chiều trước khi code.',
    avatar: '👑',
    status: 'running',
    progress: 98,
    currentTask: 'Brainstorming flow mapping & multi-agent orchestration active',
    currentStageId: 'stage_1',
    skills: ['Strategic Brainstorming', 'Interactive Flow Mapping', 'NLP Decomposition', 'Goal Alignment', 'System Prompting'],
    lastActive: '2026-09-02T06:27:00Z',
    metrics: {
      tasksCompleted: 86,
      avgResponseMs: 280,
      successRate: 99.9,
    },
  },
  {
    id: 'agent_mobile_ux',
    name: 'Mobile UX Architect',
    code: 'UX_MOBILE_430',
    category: 'FRONTEND',
    phase: 'UI/UX Design & 430px Pixel-Perfect',
    roleDescription: 'Chuyên gia giao diện Mobile-First, bảo đảm 100% chuẩn iPhone 14 Pro Max 430px viewport.',
    avatar: '📱',
    status: 'success',
    progress: 100,
    currentTask: 'Mobile 430px layout & touch targets verification passed',
    currentStageId: 'stage_3',
    skills: ['Mobile-First 430px', 'Tailwind v4', 'Touch Target Standards', 'FOUT Prevention'],
    lastActive: '2026-09-01T15:51:20Z',
    metrics: {
      tasksCompleted: 62,
      avgResponseMs: 245,
      successRate: 100.0,
    },
  },
  {
    id: 'agent_qa_subagent',
    name: 'QA Testing Subagent',
    code: 'QA_AUTOMATION',
    category: 'QA',
    phase: 'Automated Testing & Verification',
    roleDescription: 'Thực thi kiểm thử tự động đa tầng: Visual 430px, Unit Tests, E2E Browser Testing.',
    avatar: '🧪',
    status: 'running',
    progress: 88,
    currentTask: 'Running E2E Playwright Arena Simulation & RBAC Guard checks',
    currentStageId: 'stage_5',
    skills: ['Playwright E2E', 'Visual Regression 430px', 'Jest/Vitest Unit', 'Fuzz Testing'],
    lastActive: '2026-09-01T15:52:45Z',
    metrics: {
      tasksCompleted: 114,
      avgResponseMs: 180,
      successRate: 98.2,
    },
  },
  {
    id: 'agent_backend_guard',
    name: 'Backend & Supabase Realtime Guard',
    code: 'BACKEND_REALTIME',
    category: 'BACKEND',
    phase: 'Supabase Cloud & 0ms Realtime Bus',
    roleDescription: 'Bảo vệ kiến trúc Supabase Cloud 100%, đồng bộ Realtime Bus 0ms qua CustomEvent & Storage.',
    avatar: '⚡',
    status: 'running',
    progress: 92,
    currentTask: 'Dispatching Realtime 0ms Bus for Stage Updates & Battle logs',
    currentStageId: 'stage_4',
    skills: ['Supabase Cloud REST', 'Realtime Event Bus', 'PostgreSQL RLS', 'API Route Handlers'],
    lastActive: '2026-09-01T15:52:50Z',
    metrics: {
      tasksCompleted: 79,
      avgResponseMs: 140,
      successRate: 99.8,
    },
  },
  {
    id: 'agent_devops_parity',
    name: 'DevOps Parity Officer',
    code: 'DEVOPS_PARITY',
    category: 'DEVOPS',
    phase: 'Vercel Parity & Production Gate',
    roleDescription: 'Đảm bảo 100% Vercel Production Parity, TypeScript 0 lỗi, script_noibo đồng bộ.',
    avatar: '🚀',
    status: 'idle',
    progress: 75,
    currentTask: 'Standing by for Stage 7 Vercel Production Parity Gate check',
    currentStageId: 'stage_7',
    skills: ['Vercel CLI --prod', 'TypeScript Zero-Error Gate', 'CI/CD Pipelines', 'Telemetry Guard'],
    lastActive: '2026-09-01T15:50:10Z',
    metrics: {
      tasksCompleted: 53,
      avgResponseMs: 420,
      successRate: 99.1,
    },
  },
  {
    id: 'agent_rex',
    name: 'Rex (System Architect)',
    code: 'ARCH_REX',
    category: 'ARCHITECT',
    phase: 'High-Level Architecture',
    roleDescription: 'Kiến trúc sư hệ thống phân tán, thiết kế schema tối ưu và luồng dữ liệu micro-pipeline.',
    avatar: '🏛️',
    status: 'success',
    progress: 100,
    currentTask: 'Completed DB schema topology & entity mapping',
    currentStageId: 'stage_2',
    skills: ['Distributed Systems', 'Schema Design', 'Data Topology', 'Concurrency Control'],
    lastActive: '2026-09-01T15:48:00Z',
    metrics: {
      tasksCompleted: 39,
      avgResponseMs: 380,
      successRate: 100.0,
    },
  },
  {
    id: 'agent_alex',
    name: 'Alex (React & Tailwind Pro)',
    code: 'FE_ALEX',
    category: 'FRONTEND',
    phase: 'UI Component Engineering',
    roleDescription: 'Kỹ sư frontend React/Next.js, xây dựng component tương tác cao và dark-mode mượt mà.',
    avatar: '🎨',
    status: 'success',
    progress: 100,
    currentTask: 'Component suite assembly for DevOps Pipeline & 1v1 Arena',
    currentStageId: 'stage_3',
    skills: ['Next.js 14 App Router', 'Tailwind CSS', 'Radix UI / Lucide', 'Framer Motion'],
    lastActive: '2026-09-01T15:51:00Z',
    metrics: {
      tasksCompleted: 88,
      avgResponseMs: 190,
      successRate: 98.9,
    },
  },
  {
    id: 'agent_aria',
    name: 'Aria (Workflow Analyst)',
    code: 'ANALYST_ARIA',
    category: 'ANALYST',
    phase: 'Workflow & Metrics Analysis',
    roleDescription: 'Phân tích hiệu năng luồng làm việc, phát hiện điểm nghẽn và đo lường throughput squad.',
    avatar: '📊',
    status: 'running',
    progress: 85,
    currentTask: 'Analyzing Agent latency matrix & Stage execution telemetry',
    currentStageId: 'stage_5',
    skills: ['Telemetry Analytics', 'Bottleneck Detection', 'Throughput Modeling', 'SLA Monitoring'],
    lastActive: '2026-09-01T15:52:15Z',
    metrics: {
      tasksCompleted: 44,
      avgResponseMs: 270,
      successRate: 97.8,
    },
  },
  {
    id: 'agent_mason',
    name: 'Mason (Context Optimizer)',
    code: 'OPT_MASON',
    category: 'OPTIMIZER',
    phase: 'Token & Cache Compression',
    roleDescription: 'Tối ưu hóa context window, nén token hội thoại và duy trì bộ nhớ dài hạn của agent.',
    avatar: '🧠',
    status: 'idle',
    progress: 90,
    currentTask: 'Context compression caching active (saving 64% token load)',
    currentStageId: 'stage_4',
    skills: ['Context Compression', 'Vector Cache', 'Token Budgeting', 'Prompt Minification'],
    lastActive: '2026-09-01T15:49:30Z',
    metrics: {
      tasksCompleted: 71,
      avgResponseMs: 120,
      successRate: 99.7,
    },
  },
  {
    id: 'agent_luna',
    name: 'Luna (Generative UI Crafter)',
    code: 'UI_LUNA',
    category: 'FRONTEND',
    phase: 'Visual Aesthetics & Micro-interactions',
    roleDescription: 'Sáng tạo giao diện Generative UI, hiệu ứng thị giác cyberpunk/neo-brutalist và âm thanh phản hồi.',
    avatar: '✨',
    status: 'success',
    progress: 100,
    currentTask: 'Arena 1v1 Battle health bar animation & glow shaders ready',
    currentStageId: 'stage_3',
    skills: ['Generative UI', 'Micro-interactions', 'Glow Visual Effects', 'Visual Emotional Feedback'],
    lastActive: '2026-09-01T15:51:40Z',
    metrics: {
      tasksCompleted: 56,
      avgResponseMs: 210,
      successRate: 99.2,
    },
  },
  {
    id: 'agent_quinn',
    name: 'Quinn (Security Auditor & RBAC)',
    code: 'SEC_QUINN',
    category: 'QA',
    phase: 'Security & Access Auditing',
    roleDescription: 'Kiểm toán bảo mật cấp cao, siết chặt Role-Based Guard (ADMIN_CEO/HEAD vs DEV/Staff), ngăn chặn rò rỉ API.',
    avatar: '🛡️',
    status: 'running',
    progress: 94,
    currentTask: 'Validating Role Guard middleware and route access restrictions',
    currentStageId: 'stage_6',
    skills: ['Strict RBAC Guard', 'JWT Security', 'OWASP Top 10', 'Input Sanitization'],
    lastActive: '2026-09-01T15:52:35Z',
    metrics: {
      tasksCompleted: 67,
      avgResponseMs: 165,
      successRate: 100.0,
    },
  },
  {
    id: 'agent_max',
    name: 'Max (Database Architect)',
    code: 'DB_MAX',
    category: 'BACKEND',
    phase: 'Postgres & Query Optimization',
    roleDescription: 'Chuyên gia PostgreSQL & Supabase Engine, lập chỉ mục tốc độ cao, RLS Policies và Realtime replication.',
    avatar: '💾',
    status: 'success',
    progress: 100,
    currentTask: 'Optimized Realtime subscription indices on audit logs',
    currentStageId: 'stage_4',
    skills: ['PostgreSQL 16', 'RLS Policies', 'Index Optimization', 'Prisma/Supabase ORM'],
    lastActive: '2026-09-01T15:50:50Z',
    metrics: {
      tasksCompleted: 82,
      avgResponseMs: 155,
      successRate: 99.6,
    },
  },
  {
    id: 'agent_dep',
    name: 'Dep (Deployment Sentinel)',
    code: 'OPS_DEP',
    category: 'DEVOPS',
    phase: 'Release Management & Rollout',
    roleDescription: 'Giám sát hạ tầng triển khai, quản lý DNS, SSL, Edge Functions và rollback tự động khi có sự cố.',
    avatar: '🛰️',
    status: 'idle',
    progress: 70,
    currentTask: 'Edge routing health check & SSL handshake telemetry ready',
    currentStageId: 'stage_8',
    skills: ['Vercel Edge Functions', 'DNS/SSL Sentinel', 'Zero-Downtime Deploy', 'Rollback Triggers'],
    lastActive: '2026-09-01T15:47:15Z',
    metrics: {
      tasksCompleted: 42,
      avgResponseMs: 340,
      successRate: 98.5,
    },
  },
];

// ==========================================
// 2. 8 PIPELINE STAGES
// ==========================================
export const PIPELINE_STAGES: PipelineStage[] = [
  {
    id: 'stage_1',
    order: 1,
    name: 'Khởi tạo & Brainstorming Yêu cầu',
    description: 'Phân tích nghiệp vụ sâu sắc, xác định phân quyền RBAC và lộ trình thực thi squad.',
    primaryAgentCode: 'LEADER_NLP',
    status: 'completed',
    durationMs: 1820,
    logsCount: 14,
    testPassRate: 100,
    outputArtifact: 'brainstorming_specs.md',
    startedAt: '2026-09-01T15:45:00Z',
    completedAt: '2026-09-01T15:46:48Z',
  },
  {
    id: 'stage_2',
    order: 2,
    name: 'Thiết kế Kiến trúc & Database',
    description: 'Mô hình hóa dữ liệu PostgreSQL Supabase Cloud, thiết kế schema bảng và RLS rules.',
    primaryAgentCode: 'ARCH_REX',
    status: 'completed',
    durationMs: 2450,
    logsCount: 18,
    testPassRate: 100,
    outputArtifact: 'db_schema_v2.sql',
    startedAt: '2026-09-01T15:46:50Z',
    completedAt: '2026-09-01T15:49:15Z',
  },
  {
    id: 'stage_3',
    order: 3,
    name: 'Phát triển UI/UX & Responsive 430px',
    description: 'Xây dựng giao diện Touch-first, chuẩn 430px iPhone 14 Pro Max, dark-mode cyberpunk & animations.',
    primaryAgentCode: 'UX_MOBILE_430',
    status: 'completed',
    durationMs: 3120,
    logsCount: 26,
    testPassRate: 100,
    outputArtifact: 'responsive_430px_components.tsx',
    startedAt: '2026-09-01T15:49:20Z',
    completedAt: '2026-09-01T15:51:32Z',
  },
  {
    id: 'stage_4',
    order: 4,
    name: 'Backend & Supabase Realtime 0ms',
    description: 'Triển khai API Routes chuẩn Next.js 14, Supabase client và Realtime Bus gcm_*_updated.',
    primaryAgentCode: 'BACKEND_REALTIME',
    status: 'running',
    durationMs: 2150,
    logsCount: 22,
    testPassRate: 98,
    outputArtifact: 'src/lib/supabase.ts',
    startedAt: '2026-09-01T15:51:35Z',
  },
  {
    id: 'stage_5',
    order: 5,
    name: 'QA Testing Suite (Visual, Unit, E2E)',
    description: 'Chạy toàn bộ test suites: Pixel check 430px, Unit tests logic, Playwright E2E browser arena.',
    primaryAgentCode: 'QA_AUTOMATION',
    status: 'running',
    durationMs: 1980,
    logsCount: 19,
    testPassRate: 97.5,
    outputArtifact: 'test_report_full.json',
    startedAt: '2026-09-01T15:52:10Z',
  },
  {
    id: 'stage_6',
    order: 6,
    name: 'Kiểm toán Bảo mật & Phân quyền RBAC',
    description: 'Rà soát Role Guard (ADMIN_CEO/HEAD truy cập quản lý, DEV/Staff bị giới hạn), sanitization & JWT.',
    primaryAgentCode: 'SEC_QUINN',
    status: 'pending',
    durationMs: 0,
    logsCount: 0,
    startedAt: undefined,
  },
  {
    id: 'stage_7',
    order: 7,
    name: 'Kiểm định Vercel Production Parity',
    description: 'Chạy npx tsc --noEmit (0 lỗi), kiểm tra build SSR/Edge, đồng bộ tài liệu nội bộ script_noibo.docx.',
    primaryAgentCode: 'DEVOPS_PARITY',
    status: 'pending',
    durationMs: 0,
    logsCount: 0,
    startedAt: undefined,
  },
  {
    id: 'stage_8',
    order: 8,
    name: 'Bàn giao & Triển khai Production',
    description: 'Triển khai Vercel Production Live, kích hoạt Realtime telemetry and health-check monitoring.',
    primaryAgentCode: 'OPS_DEP',
    status: 'pending',
    durationMs: 0,
    logsCount: 0,
    startedAt: undefined,
  },
];

// ==========================================
// 3. STEP-BY-STEP AGENT LOGS SAMPLE DATA
// ==========================================
export const INITIAL_LOG_STEPS: AgentLogStep[] = [
  {
    id: 'log_001',
    timestamp: '2026-09-01T15:45:05Z',
    agentCode: 'LEADER_NLP',
    stageId: 'stage_1',
    stepIndex: 1,
    type: 'USER_INPUT',
    title: 'Tiếp nhận chỉ thị khởi động DevOps Pipeline & 1v1 Arena',
    thinking: 'Phân tích yêu cầu cấp bách từ người dùng: cần hệ thống điều phối Squad Agents đa vai trò, đấu trường 1v1 Arena với GitHub Trending và cơ chế Tuyển Dụng Skill tự động.',
    toolName: 'context-driven-development',
    status: 'SUCCESS',
    durationMs: 120,
  },
  {
    id: 'log_002',
    timestamp: '2026-09-01T15:45:30Z',
    agentCode: 'LEADER_NLP',
    stageId: 'stage_1',
    stepIndex: 2,
    type: 'THINKING',
    title: 'Phân rã 8 Stage Pipeline và định danh 13 Agent Chuyên biệt',
    thinking: 'Áp dụng quy tắc RBAC: Mọi màn hình Project Management & Cashflow chỉ dành cho ADMIN_CEO & HEAD. Các module Arena, GitHub Trending, DevOps Pipeline công khai cho toàn squad.',
    status: 'SUCCESS',
    durationMs: 280,
  },
  {
    id: 'log_003',
    timestamp: '2026-09-01T15:47:00Z',
    agentCode: 'ARCH_REX',
    stageId: 'stage_2',
    stepIndex: 3,
    type: 'TOOL_CALL',
    title: 'Thiết kế Schema Database Supabase Cloud',
    thinking: 'Cần cấu trúc bảng quan hệ cho stages, agents, logs, battles, và hired_skills.',
    toolName: 'write_to_file',
    toolArgs: { TargetFile: 'supabase/schema.sql', Overwrite: true },
    toolOutput: 'Created table schema with RLS security policies.',
    status: 'SUCCESS',
    durationMs: 450,
  },
  {
    id: 'log_004',
    timestamp: '2026-09-01T15:49:35Z',
    agentCode: 'UX_MOBILE_430',
    stageId: 'stage_3',
    stepIndex: 4,
    type: 'COMMAND_EXEC',
    title: 'Kiểm thử Viewport Mobile 430px cho giao diện Arena',
    thinking: 'Kiểm tra độ co giãn trên khung hình 430px x 932px (iPhone 14 Pro Max). Nút bấm font 11.5px-12.5px, height 28px-38px, padding 6px 12px.',
    commandLine: 'npx playwright test tests/mobile-430px.spec.ts',
    exitCode: 0,
    status: 'SUCCESS',
    durationMs: 1120,
  },
  {
    id: 'log_005',
    timestamp: '2026-09-01T15:51:40Z',
    agentCode: 'BACKEND_REALTIME',
    stageId: 'stage_4',
    stepIndex: 5,
    type: 'TOOL_CALL',
    title: 'Khởi tạo src/lib/supabase.ts và Realtime Event Bus',
    thinking: 'Thiết lập CustomEvent("gcm_*_updated") và storage listener để phát tín hiệu cập nhật 0ms giữa các components.',
    toolName: 'write_to_file',
    toolArgs: { TargetFile: 'src/lib/supabase.ts', Overwrite: true },
    toolOutput: 'File src/lib/supabase.ts created successfully with GCM_EVENTS.',
    status: 'SUCCESS',
    durationMs: 310,
  },
  {
    id: 'log_006',
    timestamp: '2026-09-01T15:52:15Z',
    agentCode: 'QA_AUTOMATION',
    stageId: 'stage_5',
    stepIndex: 6,
    type: 'QA_TEST',
    title: 'Chạy Test Suite Visual Pixel 430px & Solo Battle API',
    thinking: 'Kiểm tra 5 tiêu chí chấm điểm Arena 1v1: Kiến trúc, Clean Code, Tốc độ, Bảo mật RBAC, Mobile UX.',
    toolName: 'webapp-testing',
    toolOutput: 'PASS: 12/12 test cases passed with 100% assertion accuracy.',
    status: 'SUCCESS',
    durationMs: 890,
  },
];

// ==========================================
// 4. QA TEST SUITES (VISUAL 430PX, UNIT, E2E)
// ==========================================
export const INITIAL_QA_TESTS: QATestResult[] = [
  {
    id: 'qa_001',
    testSuite: 'Visual Regression Suite',
    name: 'Mobile 430px Pixel-Perfect Viewport Alignment',
    type: 'VISUAL_PIXEL_430PX',
    status: 'PASS',
    durationMs: 420,
    viewport: '430x932 (iPhone 14 Pro Max)',
    targetUrl: '/pipeline',
    details: 'Toàn bộ layout không bị vỡ hoặc ngang scrollbar. Nút bấm chuẩn 11.5px-12.5px, container flex-wrap gap 8px.',
    assertionsCount: 18,
    screenshotUrl: '/screenshots/mobile-430px-pipeline.png',
    timestamp: '2026-09-01T15:51:50Z',
  },
  {
    id: 'qa_002',
    testSuite: 'Visual Regression Suite',
    name: 'Solo Battle Arena 1v1 Mobile Card Stacking',
    type: 'VISUAL_PIXEL_430PX',
    status: 'PASS',
    durationMs: 380,
    viewport: '430x932',
    targetUrl: '/arena',
    details: 'Thẻ bài Agent và Repo tự động xếp dọc (Stack 1fr) trên màn hình < 1024px, thanh máu HP và điểm số hiển thị rõ nét.',
    assertionsCount: 14,
    screenshotUrl: '/screenshots/mobile-430px-arena.png',
    timestamp: '2026-09-01T15:52:00Z',
  },
  {
    id: 'qa_003',
    testSuite: 'Unit Test Suite',
    name: 'Realtime Bus 0ms CustomEvent Dispatch & Storage Sync',
    type: 'UNIT',
    status: 'PASS',
    durationMs: 95,
    details: 'Xác minh emitRealtimeEvent("gcm_pipeline_updated") phát CustomEvent tức thì và kích hoạt storage event listener.',
    assertionsCount: 8,
    timestamp: '2026-09-01T15:52:10Z',
  },
  {
    id: 'qa_004',
    testSuite: 'Unit Test Suite',
    name: 'Solo Battle 5-Criteria Weighted Scoring Formula',
    type: 'UNIT',
    status: 'PASS',
    durationMs: 110,
    details: 'Đảm bảo tổng trọng số = 100%, tính toán điểm chuẩn xác cho Agent vs Repo và đưa ra quyết định đúng đắn.',
    assertionsCount: 12,
    timestamp: '2026-09-01T15:52:18Z',
  },
  {
    id: 'qa_005',
    testSuite: 'E2E Browser Suite',
    name: 'Full Pipeline Stage Advancement Flow',
    type: 'E2E_BROWSER',
    status: 'PASS',
    durationMs: 940,
    targetUrl: '/pipeline',
    details: 'Mô phỏng người dùng click chuyển Stage từ 1 -> 4, kiểm tra Realtime log cập nhật ngay lập tức.',
    assertionsCount: 22,
    timestamp: '2026-09-01T15:52:25Z',
  },
  {
    id: 'qa_006',
    testSuite: 'Security RBAC Suite',
    name: 'Strict Role-Based Guard for Project Management & Cashflow',
    type: 'SECURITY_RBAC',
    status: 'PASS',
    durationMs: 160,
    details: 'DEV/Staff bị chặn 403 Forbidden khi truy cập /tools/pm-dashboard và /cashflow; ADMIN_CEO và HEAD có toàn quyền.',
    assertionsCount: 16,
    timestamp: '2026-09-01T15:52:35Z',
  },
];

// ==========================================
// 5. BASELINE GITHUB TRENDING REPOSITORIES
// ==========================================
export const BASELINE_GITHUB_REPOS: GitHubTrendingRepo[] = [
  {
    id: 101,
    name: 'autogen',
    fullName: 'microsoft/autogen',
    owner: {
      login: 'microsoft',
      avatarUrl: 'https://avatars.githubusercontent.com/u/6154722?v=4',
    },
    description: 'A programming framework for agentic AI. Build multi-agent conversation systems that act as expert teams.',
    stars: 38400,
    forks: 5600,
    language: 'Python',
    topics: ['multi-agent', 'ai-framework', 'llm-agents', 'autonomous-systems'],
    url: 'https://github.com/microsoft/autogen',
    createdAt: '2023-08-15T10:00:00Z',
    updatedAt: '2026-09-01T14:30:00Z',
    roleFitCategory: 'LEADER',
    matchedAgentCode: 'LEADER_NLP',
    agentInTeamStatus: 'ALREADY_HAVE',
    capabilitySummary: 'Framework điều phối đa tác tử mạnh mẽ của Microsoft, hỗ trợ hội thoại nhóm và tự phân bổ công việc.',
    whyUseful: 'Có thể tích hợp logic hội thoại nhóm đa agent để nâng cấp khả năng phân rã nhiệm vụ của Supreme NLP Leader.',
    isHired: false,
  },
  {
    id: 102,
    name: 'crewAI',
    fullName: 'crewAIInc/crewAI',
    owner: {
      login: 'crewAIInc',
      avatarUrl: 'https://avatars.githubusercontent.com/u/152955986?v=4',
    },
    description: 'Framework for orchestrating role-playing, autonomous AI agents. Collaborative intelligence at scale.',
    stars: 25100,
    forks: 3100,
    language: 'Python',
    topics: ['agents', 'collaboration', 'role-playing', 'orchestration'],
    url: 'https://github.com/crewAIInc/crewAI',
    createdAt: '2023-11-20T12:00:00Z',
    updatedAt: '2026-09-01T15:00:00Z',
    roleFitCategory: 'ARCHITECT',
    matchedAgentCode: 'ARCH_REX',
    agentInTeamStatus: 'ALREADY_HAVE',
    capabilitySummary: 'Mô hình hóa vai trò tác tử chuyên biệt theo crew, phân công đầu việc tuần tự và song song chuẩn xác.',
    whyUseful: 'Gia tăng năng lực phân chia quy trình cho Rex (System Architect) và phối hợp đa phòng ban.',
    isHired: false,
  },
  {
    id: 103,
    name: 'servers',
    fullName: 'modelcontextprotocol/servers',
    owner: {
      login: 'modelcontextprotocol',
      avatarUrl: 'https://avatars.githubusercontent.com/u/187932649?v=4',
    },
    description: 'Model Context Protocol (MCP) reference servers providing secure tool integrations for AI assistants.',
    stars: 19800,
    forks: 2200,
    language: 'TypeScript',
    topics: ['mcp', 'tools', 'context-protocol', 'ai-integration'],
    url: 'https://github.com/modelcontextprotocol/servers',
    createdAt: '2024-11-01T08:00:00Z',
    updatedAt: '2026-09-01T15:10:00Z',
    roleFitCategory: 'BACKEND',
    matchedAgentCode: 'BACKEND_REALTIME',
    agentInTeamStatus: 'ALREADY_HAVE',
    capabilitySummary: 'Kho máy chủ giao thức MCP chuẩn hoá giúp mở rộng công cụ kết nối hệ thống file, database và API.',
    whyUseful: 'Giúp Backend & Supabase Realtime Guard kết nối ngoại vi an toàn không giới hạn.',
    isHired: true,
  },
  {
    id: 104,
    name: 'ui',
    fullName: 'shadcn-ui/ui',
    owner: {
      login: 'shadcn-ui',
      avatarUrl: 'https://avatars.githubusercontent.com/u/139895814?v=4',
    },
    description: 'Beautifully designed components that you can copy and paste into your apps. Accessible. Customizable. Open Source.',
    stars: 76500,
    forks: 6900,
    language: 'TypeScript',
    topics: ['components', 'tailwind', 'radix-ui', 'design-system'],
    url: 'https://github.com/shadcn-ui/ui',
    createdAt: '2023-01-20T09:00:00Z',
    updatedAt: '2026-09-01T15:20:00Z',
    roleFitCategory: 'FRONTEND',
    matchedAgentCode: 'UX_MOBILE_430',
    agentInTeamStatus: 'ALREADY_HAVE',
    capabilitySummary: 'Bộ thiết kế component chuẩn mực tiếp cận cao, tối ưu Tailwind CSS và Radix UI nguyên khối.',
    whyUseful: 'Trang bị cho Mobile UX Architect và Alex để dựng giao diện 430px chuẩn UX/UI quốc tế.',
    isHired: true,
  },
  {
    id: 105,
    name: 'playwright',
    fullName: 'microsoft/playwright',
    owner: {
      login: 'microsoft',
      avatarUrl: 'https://avatars.githubusercontent.com/u/6154722?v=4',
    },
    description: 'Playwright is a framework for Web Testing and Automation. It enables cross-browser web automation.',
    stars: 68900,
    forks: 3900,
    language: 'TypeScript',
    topics: ['testing', 'automation', 'e2e', 'visual-regression', 'browser'],
    url: 'https://github.com/microsoft/playwright',
    createdAt: '2020-01-30T10:00:00Z',
    updatedAt: '2026-09-01T14:45:00Z',
    roleFitCategory: 'QA',
    matchedAgentCode: 'QA_AUTOMATION',
    agentInTeamStatus: 'ALREADY_HAVE',
    capabilitySummary: 'Công cụ test tự động hàng đầu thế giới, chụp ảnh visual so khớp pixel và giả lập touch screen 430px.',
    whyUseful: 'Vũ khí chủ lực của QA Testing Subagent để đạt 100% test pass rate trước khi release.',
    isHired: true,
  },
  {
    id: 106,
    name: 'mem0',
    fullName: 'mem0ai/mem0',
    owner: {
      login: 'mem0ai',
      avatarUrl: 'https://avatars.githubusercontent.com/u/172605912?v=4',
    },
    description: 'The Memory layer for Personalized AI. Universal memory for LLMs, agents and workflows.',
    stars: 24300,
    forks: 2400,
    language: 'Python',
    topics: ['memory', 'llm-memory', 'vector-search', 'personalization'],
    url: 'https://github.com/mem0ai/mem0',
    createdAt: '2024-04-10T11:00:00Z',
    updatedAt: '2026-09-01T13:15:00Z',
    roleFitCategory: 'OPTIMIZER',
    matchedAgentCode: 'OPT_MASON',
    agentInTeamStatus: 'ALREADY_HAVE',
    capabilitySummary: 'Lớp bộ nhớ thông minh ghi nhớ dài hạn sở thích người dùng, context qua các phiên làm việc.',
    whyUseful: 'Nâng cấp khả năng duy trì context dài hạn cho Mason (Context Optimizer).',
    isHired: false,
  },
  {
    id: 107,
    name: 'claude-engineer',
    fullName: 'Doriandark/claude-engineer',
    owner: {
      login: 'Doriandark',
      avatarUrl: 'https://avatars.githubusercontent.com/u/10452391?v=4',
    },
    description: 'An interactive CLI tool that leverages Anthropic Claude 3.5 Sonnet to assist with software engineering tasks.',
    stars: 12600,
    forks: 1600,
    language: 'Python',
    topics: ['cli', 'claude-3-5', 'coding-assistant', 'devops'],
    url: 'https://github.com/Doriandark/claude-engineer',
    createdAt: '2024-06-25T14:00:00Z',
    updatedAt: '2026-09-01T12:00:00Z',
    roleFitCategory: 'DEVOPS',
    matchedAgentCode: 'DEVOPS_PARITY',
    agentInTeamStatus: 'ALREADY_HAVE',
    capabilitySummary: 'Trợ lý CLI lập trình và quản lý DevOps trực quan với khả năng thao tác file và run command tự động.',
    whyUseful: 'Có thể bổ sung công cụ quản lý code tự động cho DevOps Parity Officer.',
    isHired: false,
  },
  {
    id: 108,
    name: 'browser-use',
    fullName: 'browser-use/browser-use',
    owner: {
      login: 'browser-use',
      avatarUrl: 'https://avatars.githubusercontent.com/u/190886105?v=4',
    },
    description: 'Make websites accessible for AI agents. Open-source web automation agent powered by LLMs.',
    stars: 31200,
    forks: 3400,
    language: 'Python',
    topics: ['web-agent', 'browser-automation', 'ai-crawler', 'vision'],
    url: 'https://github.com/browser-use/browser-use',
    createdAt: '2024-11-12T09:00:00Z',
    updatedAt: '2026-09-01T15:25:00Z',
    roleFitCategory: 'QA',
    matchedAgentCode: 'QA_AUTOMATION',
    agentInTeamStatus: 'NEW_ROLE_GAP',
    capabilitySummary: 'Agent tự động duyệt web thông minh, hiểu DOM theo ngữ cảnh và tự click form kiểm thử.',
    whyUseful: 'Khoảng trống mới: Giúp squad mở rộng khả năng kiểm thử web trực tiếp trên mọi domain công khai.',
    isHired: false,
  },
  {
    id: 109,
    name: 'gpt-researcher',
    fullName: 'assafelovic/gpt-researcher',
    owner: {
      login: 'assafelovic',
      avatarUrl: 'https://avatars.githubusercontent.com/u/13554167?v=4',
    },
    description: 'GPT Researcher is an autonomous agent designed for comprehensive online research on any topic.',
    stars: 18400,
    forks: 2300,
    language: 'Python',
    topics: ['research-agent', 'information-retrieval', 'scraping', 'synthesis'],
    url: 'https://github.com/assafelovic/gpt-researcher',
    createdAt: '2023-07-01T08:30:00Z',
    updatedAt: '2026-09-01T11:40:00Z',
    roleFitCategory: 'ANALYST',
    matchedAgentCode: 'ANALYST_ARIA',
    agentInTeamStatus: 'NEW_ROLE_GAP',
    capabilitySummary: 'Tác tử nghiên cứu độc lập tổng hợp hơn 20+ nguồn thông tin và xuất báo cáo PDF/Markdown chuyên sâu.',
    whyUseful: 'Khoảng trống mới: Cung cấp năng lực Research sâu cho Aria (Workflow Analyst) khi phân tích thị trường.',
    isHired: false,
  },
  {
    id: 110,
    name: 'open-webui',
    fullName: 'open-webui/open-webui',
    owner: {
      login: 'open-webui',
      avatarUrl: 'https://avatars.githubusercontent.com/u/156942912?v=4',
    },
    description: 'User-friendly WebUI for LLMs (Formerly Ollama WebUI). Responsive, feature-rich and self-hosted.',
    stars: 62700,
    forks: 7200,
    language: 'Svelte',
    topics: ['webui', 'ollama', 'chat-interface', 'self-hosted'],
    url: 'https://github.com/open-webui/open-webui',
    createdAt: '2023-10-05T16:00:00Z',
    updatedAt: '2026-09-01T14:50:00Z',
    roleFitCategory: 'FRONTEND',
    matchedAgentCode: 'UI_LUNA',
    agentInTeamStatus: 'ALREADY_HAVE',
    capabilitySummary: 'Giao diện Chatbot & Agent WebUI hoàn chỉnh, hỗ trợ đa mô hình, voice input và RAG pipeline.',
    whyUseful: 'Cung cấp ý tưởng thiết kế giao diện chat tương tác đa phương tiện cho Luna & Alex.',
    isHired: false,
  },
];

// ==========================================
// 6. ARENA 1V1 CRITERIA CONFIGURATION
// ==========================================
export const ARENA_EVALUATION_CRITERIA = [
  {
    id: 'crit_arch',
    name: 'Architecture & Scalability',
    nameVi: 'Kiến Trúc & Khả Năng Mở Rộng',
    weight: 0.25,
    description: 'Đánh giá độ mở rộng, thiết kế module hóa, micro-pipeline và khả năng chịu tải cao.',
  },
  {
    id: 'crit_code',
    name: 'Code Quality & Clean Code',
    nameVi: 'Chất Lượng Code & Clean Code',
    weight: 0.20,
    description: 'Đánh giá độ rõ ràng của mã nguồn, tuân thủ nguyên tắc Clean Code và TypeScript Type-Safety.',
  },
  {
    id: 'crit_speed',
    name: 'Speed & Latency Optimization',
    nameVi: 'Tốc Độ & Độ Trễ (Latency)',
    weight: 0.20,
    description: 'Đánh giá tốc độ phản hồi 0ms Realtime Bus, thời gian xử lý và tiêu tốn tài nguyên token/CPU.',
  },
  {
    id: 'crit_security',
    name: 'Security & Strict RBAC Guard',
    nameVi: 'Bảo Mật & Phân Quyền RBAC',
    weight: 0.20,
    description: 'Đánh giá tính nghiêm ngặt trong phân quyền (ADMIN_CEO/HEAD vs DEV/Staff) và kiểm soát truy cập API.',
  },
  {
    id: 'crit_mobile',
    name: 'Mobile 430px UX & Developer Experience',
    nameVi: 'Trải Nghiệm Mobile 430px & DX',
    weight: 0.15,
    description: 'Đánh giá chuẩn hiển thị 430px iPhone 14 Pro Max, touch targets và sự tiện dụng cho developer.',
  },
];
