// Central Data Store & Realtime Sync Bus
import { 
  AgentRoleProfile, 
  PipelineStage, 
  AgentLogStep, 
  QATestResult, 
  GitHubTrendingRepo, 
  SoloBattleResult, 
  HiredSkillProposal 
} from '@/types';

export const INITIAL_AGENTS: AgentRoleProfile[] = [
  {
    id: 'agent-01',
    name: 'Lead Orchestrator',
    code: 'AGENT-01',
    category: 'LEADER',
    phase: 'Giai đoạn 1 & Điều phối toàn cục',
    roleDescription: 'Phân rã task, điều phối squad 13 agents, quản lý timeline và giám sát chất lượng toàn diện.',
    avatar: '👑',
    status: 'running',
    progress: 92,
    currentTask: 'Điều phối luồng CI/CD DevOps và tổng hợp báo cáo kiểm định chất lượng',
    currentStageId: 'stage-1',
    skills: ['Subagent Orchestration', 'Task Decomposition', 'Context Bridge', 'Risk Mitigation'],
    lastActive: '10 giây trước',
    metrics: { tasksCompleted: 148, avgResponseMs: 320, successRate: 99.4 }
  },
  {
    id: 'agent-02',
    name: 'Mobile UX & Frontend Architect',
    code: 'AGENT-02',
    category: 'FRONTEND',
    phase: 'Giai đoạn 3 & Tối ưu Mobile-First',
    roleDescription: 'Thiết kế hệ thống giao diện Next.js, chuẩn hóa typography token, responsive 430px và atomic styling.',
    avatar: '📱',
    status: 'running',
    progress: 96,
    currentTask: 'Xây dựng UI Dashboard, Solo Arena Modal & Pipeline Visualizer chuẩn 430px',
    currentStageId: 'stage-3',
    skills: ['Next.js 14 App Router', 'Tailwind CSS', 'Mobile 430px Viewport', 'Atomic Components', 'CSS Tokens'],
    lastActive: 'Vừa xong',
    metrics: { tasksCompleted: 215, avgResponseMs: 240, successRate: 99.8 }
  },
  {
    id: 'agent-03',
    name: 'Backend Architect & API Designer',
    code: 'AGENT-03',
    category: 'BACKEND',
    phase: 'Giai đoạn 2 & API Contract',
    roleDescription: 'Thiết kế REST/tRPC API endpoints, định dạng dữ liệu chuẩn, xử lý nghiệp vụ Solo Arena & Realtime Bus.',
    avatar: '⚡',
    status: 'idle',
    progress: 100,
    currentTask: 'Sẵn sàng tiếp nhận API queries & Realtime broadcast synchronization',
    currentStageId: 'stage-2',
    skills: ['RESTful Design', 'Next.js Route Handlers', 'Type Safety', 'High-throughput Middleware'],
    lastActive: '1 phút trước',
    metrics: { tasksCompleted: 180, avgResponseMs: 180, successRate: 100.0 }
  },
  {
    id: 'agent-04',
    name: 'Database & Supabase Expert',
    code: 'AGENT-04',
    category: 'ARCHITECT',
    phase: 'Giai đoạn 2 & Database Architecture',
    roleDescription: 'Quản lý schema Cloud Supabase, RLS Policy, index tối ưu, loại bỏ 100% MongoDB theo chính sách.',
    avatar: '🗄️',
    status: 'success',
    progress: 100,
    currentTask: 'Đồng bộ Supabase Cloud REST Client và thiết lập RLS Policy',
    currentStageId: 'stage-2',
    skills: ['Supabase Cloud', 'PostgreSQL RLS', 'High-speed Indexing', 'Schema Migration'],
    lastActive: '3 phút trước',
    metrics: { tasksCompleted: 132, avgResponseMs: 150, successRate: 100.0 }
  },
  {
    id: 'agent-05',
    name: 'QA Playwright & Mobile Pixel Tester',
    code: 'AGENT-05',
    category: 'QA',
    phase: 'Giai đoạn 4 & 5 Kiểm thử Pixel',
    roleDescription: 'Thực thi Playwright script giả lập iPhone 14 Pro Max 430px, kiểm tra layout shift và visual regression.',
    avatar: '🎯',
    status: 'testing',
    progress: 88,
    currentTask: 'Chạy bộ test Playwright 430px: Header, Pipeline & Solo Arena components',
    currentStageId: 'stage-5',
    skills: ['Playwright E2E', 'iPhone 14 Pro Max 430px', 'Visual Regression', 'Snapshot Assertions'],
    lastActive: '5 giây trước',
    metrics: { tasksCompleted: 310, avgResponseMs: 410, successRate: 98.9 }
  },
  {
    id: 'agent-06',
    name: 'Security & RBAC Guard Auditor',
    code: 'AGENT-06',
    category: 'ARCHITECT',
    phase: 'Giai đoạn 6 & Phân quyền bảo mật',
    roleDescription: 'Kiểm tra nghiêm ngặt quyền truy cập ADMIN_CEO vs HEAD vs DEV/QA/STAFF, bảo vệ dữ liệu nhạy cảm.',
    avatar: '🛡️',
    status: 'success',
    progress: 100,
    currentTask: 'Audit phân quyền Strict Role-Based Guard cho toàn bộ màn hình',
    currentStageId: 'stage-6',
    skills: ['RBAC Guard', 'JWT Security', 'OWASP Top 10', 'Endpoint Shielding'],
    lastActive: '2 phút trước',
    metrics: { tasksCompleted: 95, avgResponseMs: 210, successRate: 100.0 }
  },
  {
    id: 'agent-07',
    name: 'DevOps & Vercel Parity Specialist',
    code: 'AGENT-07',
    category: 'DEVOPS',
    phase: 'Giai đoạn 8 & Triển khai Production',
    roleDescription: 'Đảm bảo 100% Vercel Production Parity, kiểm tra type check npx tsc --noEmit và script_noibo.docx.',
    avatar: '🚀',
    status: 'running',
    progress: 85,
    currentTask: 'Build verification, zero typescript errors và chuẩn bị Vercel Deploy',
    currentStageId: 'stage-8',
    skills: ['Vercel Edge Platform', 'TypeScript Zero-Error', 'CI/CD Pipelines', 'Automated Release'],
    lastActive: '20 giây trước',
    metrics: { tasksCompleted: 165, avgResponseMs: 520, successRate: 99.1 }
  },
  {
    id: 'agent-08',
    name: 'Performance & Observability Engineer',
    code: 'AGENT-08',
    category: 'OPTIMIZER',
    phase: 'Giai đoạn 7 & Giám sát hiệu năng',
    roleDescription: 'Đo lường Core Web Vitals, FCP, LCP, CLS, phân tích memory leaks và tối ưu tốc độ render.',
    avatar: '📊',
    status: 'idle',
    progress: 95,
    currentTask: 'Giám sát FPS và tốc độ chuyển đổi giữa các Tabs < 16ms',
    currentStageId: 'stage-7',
    skills: ['Core Web Vitals', 'FPS Profiling', 'Bundle Analyzer', 'Memory Optimization'],
    lastActive: '4 phút trước',
    metrics: { tasksCompleted: 88, avgResponseMs: 190, successRate: 99.5 }
  },
  {
    id: 'agent-09',
    name: 'Web Interface & Design System Specialist',
    code: 'AGENT-09',
    category: 'FRONTEND',
    phase: 'Giai đoạn 3 & Design Token System',
    roleDescription: 'Quản trị hệ thống CSS Variables: font 11.5px-12.5px, height 28px-38px, glow effects và Dark Mode.',
    avatar: '🎨',
    status: 'idle',
    progress: 100,
    currentTask: 'Chuẩn hóa Design Tokens & CSS Variables trên toàn bộ components',
    currentStageId: 'stage-3',
    skills: ['Design Tokens', 'Dark Theme UX', 'Accessibility WCAG', 'Micro-interactions'],
    lastActive: '6 phút trước',
    metrics: { tasksCompleted: 142, avgResponseMs: 230, successRate: 100.0 }
  },
  {
    id: 'agent-10',
    name: 'GitHub Trending Hunter & Evaluator',
    code: 'AGENT-10',
    category: 'ANALYST',
    phase: 'Giai đoạn 1 & Nghiên cứu Công nghệ',
    roleDescription: 'Quét Top 10 GitHub Trending Repositories hàng ngày, đánh giá khả năng tuyển dụng và bổ sung vào squad.',
    avatar: '🔭',
    status: 'running',
    progress: 94,
    currentTask: 'Phân tích Top 10 GitHub AI & Developer Repos mới nhất và mapping vào Squad',
    currentStageId: 'stage-1',
    skills: ['GitHub API Scraping', 'Tech Stack Evaluation', 'Capability Gap Analysis', 'Trend Forecasting'],
    lastActive: 'Vừa xong',
    metrics: { tasksCompleted: 275, avgResponseMs: 380, successRate: 98.7 }
  },
  {
    id: 'agent-11',
    name: 'Solo Battle Arena Adjudicator',
    code: 'AGENT-11',
    category: 'ANALYST',
    phase: 'Giai đoạn 1 & So găng 1v1',
    roleDescription: 'Trọng tài điều hành đấu trường Solo 1v1 giữa Squad Agent vs Top Repo, chấm điểm 5 tiêu chí độc lập.',
    avatar: '⚔️',
    status: 'running',
    progress: 90,
    currentTask: 'Điều hành trận đấu Solo 1v1: v0-clone vs AGENT-02 Mobile UX Architect',
    currentStageId: 'stage-1',
    skills: ['Comparative Scoring', '5-Dimension Rubric', 'Technical Debate', 'Hiring Recommendation'],
    lastActive: 'Vừa xong',
    metrics: { tasksCompleted: 64, avgResponseMs: 450, successRate: 99.2 }
  },
  {
    id: 'agent-12',
    name: 'Code Reviewer & Clean Code Guardian',
    code: 'AGENT-12',
    category: 'ARCHITECT',
    phase: 'Giai đoạn 4 & Clean Code Review',
    roleDescription: 'Đánh giá cấu trúc code theo nguyên lý Clean Code của Uncle Bob, phát hiện code smell và refactoring.',
    avatar: '🔍',
    status: 'idle',
    progress: 100,
    currentTask: 'Hoàn thành review 12 components React/Next.js - Đạt chuẩn Clean Code',
    currentStageId: 'stage-4',
    skills: ['Clean Code Principles', 'SOLID Architecture', 'Refactoring', 'Pattern Matching'],
    lastActive: '5 phút trước',
    metrics: { tasksCompleted: 198, avgResponseMs: 290, successRate: 100.0 }
  },
  {
    id: 'agent-13',
    name: 'Context & Agent Memory Manager',
    code: 'AGENT-13',
    category: 'OPTIMIZER',
    phase: 'Giai đoạn 1-8 & Quản trị Bộ nhớ',
    roleDescription: 'Quản lý Hybrid Agent Memory, lưu trữ kiến thức tiến hóa, nén context window và truyền tải tri thức.',
    avatar: '🧠',
    status: 'idle',
    progress: 100,
    currentTask: 'Đồng bộ hóa Persistent Memory & Context Vector cho 13 Subagents',
    currentStageId: 'stage-1',
    skills: ['Hybrid Memory System', 'Vector Search', 'Context Window Compression', 'Knowledge Graph'],
    lastActive: '7 phút trước',
    metrics: { tasksCompleted: 110, avgResponseMs: 160, successRate: 100.0 }
  }
];

export const PIPELINE_STAGES: PipelineStage[] = [
  {
    id: 'stage-1',
    order: 1,
    name: 'Phân tích Yêu cầu & Kiến trúc Squad',
    description: 'Leader phân rã yêu cầu, định hình kiến trúc toàn cục và điều phối 13 subagents.',
    primaryAgentCode: 'AGENT-01',
    status: 'completed',
    durationMs: 4200,
    logsCount: 14,
    testPassRate: 100,
    outputArtifact: 'architecture_specification.md',
    startedAt: '15:40:02',
    completedAt: '15:40:06',
  },
  {
    id: 'stage-2',
    order: 2,
    name: 'Thiết kế Schema & API Contract',
    description: 'Thiết lập Supabase REST Client, RLS Policy và API typesafety.',
    primaryAgentCode: 'AGENT-03',
    status: 'completed',
    durationMs: 3800,
    logsCount: 18,
    testPassRate: 100,
    outputArtifact: 'src/types/index.ts',
    startedAt: '15:40:07',
    completedAt: '15:40:11',
  },
  {
    id: 'stage-3',
    order: 3,
    name: 'Phát triển Giao diện Mobile UX & Frontend',
    description: 'Xây dựng toàn bộ hệ thống React components, CSS tokens và Dark Mode UI.',
    primaryAgentCode: 'AGENT-02',
    status: 'completed',
    durationMs: 7600,
    logsCount: 32,
    testPassRate: 100,
    outputArtifact: 'src/components/*',
    startedAt: '15:40:12',
    completedAt: '15:40:20',
  },
  {
    id: 'stage-4',
    order: 4,
    name: 'Kiểm thử Đơn vị & Tích hợp (Unit & Integration)',
    description: 'Chạy toàn bộ test suites cho RBAC guards, calculations và data adapters.',
    primaryAgentCode: 'AGENT-12',
    status: 'completed',
    durationMs: 2900,
    logsCount: 22,
    testPassRate: 100,
    outputArtifact: 'unit_test_report.json',
    startedAt: '15:40:21',
    completedAt: '15:40:24',
  },
  {
    id: 'stage-5',
    order: 5,
    name: 'Visual Regression 430px Pixel-Perfect',
    description: 'Playwright giả lập iPhone 14 Pro Max (430px width), xác minh zero layout shift.',
    primaryAgentCode: 'AGENT-05',
    status: 'completed',
    durationMs: 5100,
    logsCount: 28,
    testPassRate: 98.5,
    outputArtifact: 'playwright_visual_430px.png',
    startedAt: '15:40:25',
    completedAt: '15:40:30',
  },
  {
    id: 'stage-6',
    order: 6,
    name: 'Kiểm toán Bảo mật & Phân quyền RBAC',
    description: 'Xác minh phân quyền nghiêm ngặt ADMIN_CEO vs HEAD vs DEV/QA/STAFF.',
    primaryAgentCode: 'AGENT-06',
    status: 'completed',
    durationMs: 2100,
    logsCount: 16,
    testPassRate: 100,
    outputArtifact: 'security_audit_report.json',
    startedAt: '15:40:31',
    completedAt: '15:40:33',
  },
  {
    id: 'stage-7',
    order: 7,
    name: 'Kiểm thử End-to-End & Observability',
    description: 'Playwright chạy toàn bộ kịch bản người dùng: Solo Battle, Hiring và Tab switching.',
    primaryAgentCode: 'AGENT-08',
    status: 'running',
    durationMs: 3400,
    logsCount: 19,
    testPassRate: 97.8,
    outputArtifact: 'e2e_user_journey.json',
    startedAt: '15:40:34',
  },
  {
    id: 'stage-8',
    order: 8,
    name: 'Build Production & Vercel Cloud Parity',
    description: 'Kiểm tra npx tsc --noEmit 0 lỗi và chuẩn bị đồng bộ Vercel Cloud.',
    primaryAgentCode: 'AGENT-07',
    status: 'pending',
    durationMs: 0,
    logsCount: 8,
    testPassRate: 0,
    outputArtifact: '.next/standalone',
  }
];

export const INITIAL_LOGS: AgentLogStep[] = [
  {
    id: 'log-01',
    timestamp: '15:40:02.102',
    agentCode: 'AGENT-01',
    stageId: 'stage-1',
    stepIndex: 1,
    type: 'USER_INPUT',
    title: 'Tiếp nhận Chỉ thị Toàn Cục từ Quản Trị Viên',
    toolOutput: 'Yêu cầu: Xây dựng hệ thống Agent Squad DevOps Arena, GitHub Trending Hunter và Solo 1v1 Battle.',
    status: 'SUCCESS',
    durationMs: 120,
  },
  {
    id: 'log-02',
    timestamp: '15:40:02.320',
    agentCode: 'AGENT-01',
    stageId: 'stage-1',
    stepIndex: 2,
    type: 'THINKING',
    title: 'Phân tích Chiến lược Phân rã 13 Subagents & 8 Giai đoạn CI/CD',
    thinking: 'Phân rã hệ thống thành 13 Subagents và 8 giai đoạn CI/CD khép kín. Mỗi agent phụ trách một vai trò chuyên sâu với metrics và SLA rõ ràng.',
    status: 'SUCCESS',
    durationMs: 450,
  },
  {
    id: 'log-03',
    timestamp: '15:40:03.110',
    agentCode: 'AGENT-01',
    stageId: 'stage-1',
    stepIndex: 3,
    type: 'TOOL_CALL',
    title: 'Kích hoạt Subagents Chuyên Biệt',
    toolName: 'invoke_subagent',
    toolArgs: {
      subagents: ['AGENT-02: Mobile UX', 'AGENT-03: Backend', 'AGENT-05: QA Tester', 'AGENT-06: Security']
    },
    toolOutput: 'Successfully spawned 4 specialized subagents in isolated contexts.',
    status: 'SUCCESS',
    durationMs: 310,
  },
  {
    id: 'log-04',
    timestamp: '15:40:07.450',
    agentCode: 'AGENT-03',
    stageId: 'stage-2',
    stepIndex: 4,
    type: 'COMMAND_EXEC',
    title: 'Khởi tạo Supabase REST Client & Schema Contract',
    commandLine: 'python build_types.py && npx supabase gen types typescript',
    exitCode: 0,
    toolOutput: 'Generated TypeScript interfaces with 100% strict type safety.',
    status: 'SUCCESS',
    durationMs: 820,
  },
  {
    id: 'log-05',
    timestamp: '15:40:12.180',
    agentCode: 'AGENT-02',
    stageId: 'stage-3',
    stepIndex: 5,
    type: 'THINKING',
    title: 'Kiến trúc Giao diện Mobile-First & CSS Variable Design Tokens',
    thinking: 'Áp dụng nguyên tắc UX/UI nghiêm ngặt: Button typography font 11.5px - 12.5px, height 28px - 38px, padding 6px 12px, whiteSpace nowrap. Responsive < 1024px stack 1fr.',
    status: 'SUCCESS',
    durationMs: 560,
  },
  {
    id: 'log-06',
    timestamp: '15:40:15.920',
    agentCode: 'AGENT-02',
    stageId: 'stage-3',
    stepIndex: 6,
    type: 'TOOL_CALL',
    title: 'Tạo Hệ thống 9 React Components',
    toolName: 'write_to_file',
    toolArgs: {
      files: [
        'src/components/Header.tsx',
        'src/components/PipelineVisualizer.tsx',
        'src/components/AgentStatusMatrix.tsx',
        'src/components/AgentLogInspectorModal.tsx',
        'src/components/QATestingPanel.tsx',
        'src/components/GitHubTrendingHunter.tsx',
        'src/components/AgentSoloArenaModal.tsx',
        'src/components/HiringProposalsList.tsx',
        'src/components/RoleGuardBanner.tsx'
      ]
    },
    toolOutput: 'All 9 components generated successfully with atomic design hierarchy.',
    status: 'SUCCESS',
    durationMs: 1450,
  },
  {
    id: 'log-07',
    timestamp: '15:40:22.340',
    agentCode: 'AGENT-12',
    stageId: 'stage-4',
    stepIndex: 7,
    type: 'QA_TEST',
    title: 'Kiểm thử Clean Code & Đơn vị RBAC Functions',
    commandLine: 'npm test -- --coverage',
    exitCode: 0,
    toolOutput: 'PASS: 24/24 unit tests passed. Code coverage: 96.4%. Zero code smells detected.',
    status: 'SUCCESS',
    durationMs: 980,
  },
  {
    id: 'log-08',
    timestamp: '15:40:26.110',
    agentCode: 'AGENT-05',
    stageId: 'stage-5',
    stepIndex: 8,
    type: 'QA_TEST',
    title: 'Playwright iPhone 14 Pro Max 430px Visual Regression Test',
    commandLine: 'playwright test tests/mobile-430px.spec.ts --project="Mobile Chrome"',
    exitCode: 0,
    toolOutput: 'Verified 430px viewport: Zero horizontal overflow, button wrap clean, touch targets >= 32px.',
    status: 'SUCCESS',
    durationMs: 2450,
  },
  {
    id: 'log-09',
    timestamp: '15:40:31.890',
    agentCode: 'AGENT-06',
    stageId: 'stage-6',
    stepIndex: 9,
    type: 'QA_TEST',
    title: 'Kiểm toán Phân quyền RBAC Guard Security',
    toolOutput: 'Strict Role-Based Guard verified: DEV/QA/STAFF blocked from CEO/HEAD sensitive controls with RoleGuardBanner.',
    status: 'SUCCESS',
    durationMs: 640,
  },
  {
    id: 'log-10',
    timestamp: '15:40:35.040',
    agentCode: 'AGENT-10',
    stageId: 'stage-7',
    stepIndex: 10,
    type: 'OUTPUT',
    title: 'Hoàn thành Quét Top 10 GitHub Trending Repos',
    toolOutput: 'Đã phân tích 10 Repositories xu hướng AI & Frontend. 5 Repos đã có trong Squad, 5 Repos mở cơ hội Tuyển dụng.',
    status: 'SUCCESS',
    durationMs: 780,
  }
];

export const INITIAL_QA_TESTS: QATestResult[] = [
  {
    id: 'qa-01',
    testSuite: 'Mobile-First & 430px Viewport',
    name: 'iPhone 14 Pro Max 430px Visual Regression',
    type: 'VISUAL_PIXEL_430PX',
    status: 'PASS',
    durationMs: 380,
    viewport: '430x932',
    targetUrl: '/?viewport=mobile_430px',
    details: 'Xác nhận không có phần tử nào bị tràn viền (zero horizontal scroll), button font chuẩn 11.5px-12.5px.',
    assertionsCount: 16,
    timestamp: '15:40:26',
  },
  {
    id: 'qa-02',
    testSuite: 'Mobile-First & 430px Viewport',
    name: 'Touch Target & Button Wrapping Test',
    type: 'VISUAL_PIXEL_430PX',
    status: 'PASS',
    durationMs: 290,
    viewport: '430x932',
    targetUrl: '/#btn-container',
    details: 'Mọi nút bấm đạt chiều cao >= 28px và <= 38px, padding 6px 12px, container flex-wrap chuẩn.',
    assertionsCount: 12,
    timestamp: '15:40:27',
  },
  {
    id: 'qa-03',
    testSuite: 'Responsive Breakpoints',
    name: 'Stack 1fr Layout on < 1024px Screen',
    type: 'RESPONSIVE_BREAKPOINTS',
    status: 'PASS',
    durationMs: 450,
    viewport: '768x1024',
    targetUrl: '/#agent-matrix',
    details: 'Lưới AgentStatusMatrix và Top GitHub Repos tự động chuyển sang 1 cột (1fr) trên tablet và mobile.',
    assertionsCount: 8,
    timestamp: '15:40:28',
  },
  {
    id: 'qa-04',
    testSuite: 'Security & RBAC',
    name: 'Strict Role-Based Guard for DEV/QA',
    type: 'SECURITY_RBAC',
    status: 'PASS',
    durationMs: 190,
    targetUrl: '/tools/pm-dashboard',
    details: 'Chặn quyền truy cập của role DEV/QA vào các thao tác nhạy cảm của CEO/HEAD, hiển thị RoleGuardBanner.',
    assertionsCount: 14,
    timestamp: '15:40:31',
  },
  {
    id: 'qa-05',
    testSuite: 'E2E User Journey',
    name: 'Solo Battle 1v1 & Hire Proposal Flow',
    type: 'E2E_BROWSER',
    status: 'PASS',
    durationMs: 1240,
    viewport: '1440x900',
    targetUrl: '/#solo-arena',
    details: 'Kiểm thử toàn bộ luồng: Chọn Repo -> Mở Arena 1v1 -> So găng 5 tiêu chí -> Đề xuất tuyển dụng -> Realtime sync.',
    assertionsCount: 22,
    timestamp: '15:40:34',
  },
  {
    id: 'qa-06',
    testSuite: 'Unit Test & Calculations',
    name: 'Solo Battle Weighted Score Calculation',
    type: 'UNIT',
    status: 'PASS',
    durationMs: 65,
    details: 'Tính toán chính xác trọng số 5 tiêu chí điểm số: Hoàn thiện (25%), Mobile 430px (25%), RBAC (20%), Hiệu năng (15%), Synergy (15%).',
    assertionsCount: 30,
    timestamp: '15:40:22',
  },
  {
    id: 'qa-07',
    testSuite: 'Integration & Realtime Bus',
    name: 'Realtime Bus 0ms Event Dispatching',
    type: 'INTEGRATION',
    status: 'PASS',
    durationMs: 110,
    details: 'Kiểm tra CustomEvent("gcm_*_updated") và window storage event broadcast đồng bộ 0ms.',
    assertionsCount: 10,
    timestamp: '15:40:23',
  }
];

export const GITHUB_TRENDING_REPOS: GitHubTrendingRepo[] = [
  {
    id: 101,
    name: 'ui',
    fullName: 'shadcn-ui/ui',
    owner: {
      login: 'shadcn',
      avatarUrl: 'https://avatars.githubusercontent.com/u/124599?v=4',
    },
    description: 'Beautifully designed components that you can copy and paste into your apps. Accessible. Customizable. Open Source.',
    stars: 76500,
    forks: 6400,
    language: 'TypeScript',
    topics: ['react', 'tailwind', 'radix-ui', 'components', 'ui'],
    url: 'https://github.com/shadcn-ui/ui',
    createdAt: '2023-01-20',
    updatedAt: '2026-09-01',
    roleFitCategory: 'FRONTEND',
    matchedAgentCode: 'AGENT-09',
    agentInTeamStatus: 'ALREADY_HAVE',
    capabilitySummary: 'Thư viện UI Components chuẩn Design Token và Tailwind CSS.',
    whyUseful: 'Cung cấp nền tảng design system đồng nhất cho các giao diện Dashboard của Squad.',
  },
  {
    id: 102,
    name: 'v0-clone',
    fullName: 'v0-community/v0-clone',
    owner: {
      login: 'v0-community',
      avatarUrl: 'https://avatars.githubusercontent.com/u/987456?v=4',
    },
    description: 'Open-source Generative UI Builder with real-time Next.js & Tailwind instant live sandbox preview.',
    stars: 34200,
    forks: 3100,
    language: 'TypeScript',
    topics: ['generative-ui', 'ai-coding', 'nextjs', 'tailwind', 'sandbox'],
    url: 'https://github.com/v0-community/v0-clone',
    createdAt: '2024-03-15',
    updatedAt: '2026-09-01',
    roleFitCategory: 'FRONTEND',
    matchedAgentCode: 'AGENT-02',
    agentInTeamStatus: 'NEW_ROLE_GAP',
    capabilitySummary: 'Sinh giao diện React thời gian thực từ prompt người dùng kèm Sandbox Preview tương tác trực tiếp.',
    whyUseful: 'Có thể tích hợp làm Skill sinh nhanh giao diện cho AGENT-02 Mobile UX Architect.',
  },
  {
    id: 103,
    name: 'playwright',
    fullName: 'microsoft/playwright',
    owner: {
      login: 'microsoft',
      avatarUrl: 'https://avatars.githubusercontent.com/u/6154722?v=4',
    },
    description: 'Playwright is a framework for Web Testing and Automation. It allows testing Chromium, Firefox and WebKit with a single API.',
    stars: 68900,
    forks: 4100,
    language: 'TypeScript',
    topics: ['testing', 'automation', 'e2e', 'visual-regression', 'mobile-emulation'],
    url: 'https://github.com/microsoft/playwright',
    createdAt: '2020-01-31',
    updatedAt: '2026-09-01',
    roleFitCategory: 'QA',
    matchedAgentCode: 'AGENT-05',
    agentInTeamStatus: 'ALREADY_HAVE',
    capabilitySummary: 'Framework kiểm thử E2E và giả lập Mobile Viewport 430px mạnh mẽ nhất.',
    whyUseful: 'Cốt lõi cho AGENT-05 thực thi bộ test Playwright 430px Pixel-Perfect.',
  },
  {
    id: 104,
    name: 'langgraph',
    fullName: 'langchain-ai/langgraph',
    owner: {
      login: 'langchain-ai',
      avatarUrl: 'https://avatars.githubusercontent.com/u/126733545?v=4',
    },
    description: 'Build resilient language agents as graphs. Orchestrate cyclic multi-agent teams with fault-tolerance.',
    stars: 21800,
    forks: 2300,
    language: 'Python',
    topics: ['multi-agent', 'state-graph', 'llm-orchestration', 'fault-tolerance'],
    url: 'https://github.com/langchain-ai/langgraph',
    createdAt: '2024-01-10',
    updatedAt: '2026-09-01',
    roleFitCategory: 'LEADER',
    matchedAgentCode: 'AGENT-01',
    agentInTeamStatus: 'NEW_ROLE_GAP',
    capabilitySummary: 'Mô hình hóa quy trình đa tác tử dạng State Graph có khả năng tự phục hồi lỗi.',
    whyUseful: 'Nâng cấp khả năng điều phối phân nhánh song song cho AGENT-01 Lead Orchestrator.',
  },
  {
    id: 105,
    name: 'supabase',
    fullName: 'supabase/supabase',
    owner: {
      login: 'supabase',
      avatarUrl: 'https://avatars.githubusercontent.com/u/54469796?v=4',
    },
    description: 'The open source Firebase alternative. Supabase gives you a dedicated Postgres database with Realtime & Auth.',
    stars: 74100,
    forks: 6900,
    language: 'TypeScript',
    topics: ['postgres', 'realtime', 'auth', 'database', 'rest-api'],
    url: 'https://github.com/supabase/supabase',
    createdAt: '2020-05-18',
    updatedAt: '2026-09-01',
    roleFitCategory: 'ARCHITECT',
    matchedAgentCode: 'AGENT-04',
    agentInTeamStatus: 'ALREADY_HAVE',
    capabilitySummary: 'Hạ tầng Cloud Supabase với Postgres, Realtime WebSockets và RLS Security.',
    whyUseful: 'Nền tảng Database duy nhất được sử dụng theo quy định của hệ thống Squad.',
  },
  {
    id: 106,
    name: 'deepseek-coder-eval',
    fullName: 'deepseek-ai/deepseek-coder',
    owner: {
      login: 'deepseek-ai',
      avatarUrl: 'https://avatars.githubusercontent.com/u/148330837?v=4',
    },
    description: 'DeepSeek-Coder: Let the Code Write Itself. Advanced Code Reasoning, Refactoring & Benchmarking.',
    stars: 28500,
    forks: 2700,
    language: 'Python',
    topics: ['code-llm', 'clean-code', 'code-review', 'refactoring', 'benchmarks'],
    url: 'https://github.com/deepseek-ai/deepseek-coder',
    createdAt: '2023-11-28',
    updatedAt: '2026-09-01',
    roleFitCategory: 'ARCHITECT',
    matchedAgentCode: 'AGENT-12',
    agentInTeamStatus: 'NEW_ROLE_GAP',
    capabilitySummary: 'Mô hình đánh giá chất lượng mã nguồn, tự động đề xuất refactoring Clean Code.',
    whyUseful: 'Có thể tích hợp vào AGENT-12 để chấm điểm Clean Code theo thang điểm Uncle Bob.',
  },
  {
    id: 107,
    name: 'trpc',
    fullName: 'trpc/trpc',
    owner: {
      login: 'trpc',
      avatarUrl: 'https://avatars.githubusercontent.com/u/78411052?v=4',
    },
    description: 'Move Fast and Break Nothing. End-to-end typesafe APIs made easy.',
    stars: 36100,
    forks: 1400,
    language: 'TypeScript',
    topics: ['typescript', 'api', 'typesafe', 'rpc', 'developer-experience'],
    url: 'https://github.com/trpc/trpc',
    createdAt: '2020-07-25',
    updatedAt: '2026-09-01',
    roleFitCategory: 'BACKEND',
    matchedAgentCode: 'AGENT-03',
    agentInTeamStatus: 'ALREADY_HAVE',
    capabilitySummary: 'Cơ chế API typesafety 100% từ Server đến Client không cần code gen.',
    whyUseful: 'Giúp AGENT-03 duy trì API contract chuẩn xác tuyệt đối không lỗi runtime.',
  },
  {
    id: 108,
    name: 'turborepo',
    fullName: 'vercel/turborepo',
    owner: {
      login: 'vercel',
      avatarUrl: 'https://avatars.githubusercontent.com/u/14985020?v=4',
    },
    description: 'Build system for JavaScript and TypeScript codebases that makes your build fast and smart.',
    stars: 26300,
    forks: 1900,
    language: 'Rust',
    topics: ['build-system', 'monorepo', 'caching', 'devops', 'turbopack'],
    url: 'https://github.com/vercel/turborepo',
    createdAt: '2021-12-09',
    updatedAt: '2026-09-01',
    roleFitCategory: 'DEVOPS',
    matchedAgentCode: 'AGENT-07',
    agentInTeamStatus: 'ALREADY_HAVE',
    capabilitySummary: 'Hệ thống build monorepo siêu tốc với Remote Caching.',
    whyUseful: 'Tối ưu tốc độ build CI/CD cho AGENT-07 Vercel DevOps Specialist.',
  },
  {
    id: 109,
    name: 'supermemory',
    fullName: 'supermemoryai/supermemory',
    owner: {
      login: 'supermemoryai',
      avatarUrl: 'https://avatars.githubusercontent.com/u/161864112?v=4',
    },
    description: 'Build your own second brain with AI. Persistent context memory graph for LLMs and autonomous agents.',
    stars: 19400,
    forks: 1600,
    language: 'TypeScript',
    topics: ['memory-graph', 'agent-context', 'vector-search', 'ai-memory'],
    url: 'https://github.com/supermemoryai/supermemory',
    createdAt: '2024-04-12',
    updatedAt: '2026-09-01',
    roleFitCategory: 'OPTIMIZER',
    matchedAgentCode: 'AGENT-13',
    agentInTeamStatus: 'NEW_ROLE_GAP',
    capabilitySummary: 'Hệ thống đồ thị bộ nhớ dài hạn giúp tác tử ghi nhớ lịch sử và ngữ cảnh phức tạp.',
    whyUseful: 'Mở rộng khả năng lưu trữ trí nhớ liên tục cho AGENT-13 Context Memory Manager.',
  },
  {
    id: 110,
    name: 'ai-sre-telemetry',
    fullName: 'sentry-realtime/ai-sre-telemetry',
    owner: {
      login: 'sentry-realtime',
      avatarUrl: 'https://avatars.githubusercontent.com/u/101859?v=4',
    },
    description: 'Next-Gen Autonomous SRE & Realtime Observability Platform for AI Workflows.',
    stars: 15700,
    forks: 1100,
    language: 'TypeScript',
    topics: ['observability', 'telemetry', 'sre', 'ai-monitoring', 'metrics'],
    url: 'https://github.com/sentry-realtime/ai-sre-telemetry',
    createdAt: '2024-05-02',
    updatedAt: '2026-09-01',
    roleFitCategory: 'OPTIMIZER',
    matchedAgentCode: 'AGENT-08',
    agentInTeamStatus: 'NEW_ROLE_GAP',
    capabilitySummary: 'Giám sát chỉ số thời gian thực và tự động phát hiện nghẽn mạng hoặc tràn RAM.',
    whyUseful: 'Bổ trợ công cụ đo lường hiệu năng cao cấp cho AGENT-08 Observability Engineer.',
  }
];

export const INITIAL_SOLO_BATTLES: Record<string, SoloBattleResult> = {
  'v0-community/v0-clone': {
    id: 'battle-01',
    repoFullName: 'v0-community/v0-clone',
    repoName: 'v0-clone',
    agentCode: 'AGENT-02',
    agentName: 'Mobile UX & Frontend Architect',
    matchDate: '2026-09-01 15:45',
    winner: 'AGENT',
    scoreRepo: 87,
    scoreAgent: 96,
    criteriaScores: [
      {
        name: 'Architecture & Code Maturity',
        nameVi: 'Độ hoàn thiện & Kiến trúc Code',
        repoScore: 88,
        agentScore: 95,
        weight: 0.25,
        analysis: 'AGENT-02 áp dụng cấu trúc Atomic & Design Tokens chuẩn xác, tách biệt rõ ràng giữa Presentation và Logic.',
      },
      {
        name: 'Mobile-First 430px Parity',
        nameVi: 'Tối ưu Mobile-First & Responsive 430px',
        repoScore: 82,
        agentScore: 98,
        weight: 0.25,
        analysis: 'AGENT-02 đạt 100% tuân thủ viewport iPhone 14 Pro Max 430px với zero layout shift và button wrapping chuẩn.',
      },
      {
        name: 'Security & RBAC Strictness',
        nameVi: 'Tuân thủ Bảo mật & Phân quyền RBAC',
        repoScore: 78,
        agentScore: 94,
        weight: 0.20,
        analysis: 'AGENT-02 tích hợp RoleGuardBanner và kiểm soát trạng thái tương tác theo phân cấp CEO/HEAD/DEV.',
      },
      {
        name: 'Performance & Latency',
        nameVi: 'Hiệu năng & Tốc độ thực thi',
        repoScore: 92,
        agentScore: 96,
        weight: 0.15,
        analysis: 'AGENT-02 tối ưu render mượt mà 60 FPS, kích thước bundle tối giản không phụ thuộc runtime nặng.',
      },
      {
        name: 'Squad Synergy & Integration Ease',
        nameVi: 'Độ tương thích & Khả năng phối hợp',
        repoScore: 96,
        agentScore: 98,
        weight: 0.15,
        analysis: 'Khả năng sinh component tức thì của v0-clone rất giá trị để nhập làm Skill hỗ trợ cho AGENT-02.',
      }
    ],
    battleLog: [
      {
        round: 1,
        topic: 'Hiệp 1: Thiết kế Responsive & Chuẩn Typography Mobile 430px',
        commentary: 'AGENT-02 thể hiện sự vượt trội với quy chuẩn nút bấm 11.5px-12.5px, height 28px-38px và flex-wrap hoàn hảo trên viewport 430px.',
        advantage: 'AGENT',
      },
      {
        round: 2,
        topic: 'Hiệp 2: Tốc độ sinh giao diện & Sandbox Live Preview',
        commentary: 'v0-clone phản công mạnh mẽ với khả năng sinh mockup tức thời trong Live Sandbox, ghi điểm ấn tượng.',
        advantage: 'REPO',
      },
      {
        round: 3,
        topic: 'Hiệp 3: Tích hợp Supabase & Realtime Bus 0ms',
        commentary: 'AGENT-02 làm chủ hoàn toàn giao tiếp CustomEvent("gcm_*_updated") và Supabase REST Cloud không gián đoạn.',
        advantage: 'AGENT',
      },
      {
        round: 4,
        topic: 'Hiệp 4: Tổng kết Phán quyết & Đánh giá Tuyển dụng',
        commentary: 'AGENT-02 giành chiến thắng thuyết phục (96 vs 87). Tuy nhiên năng lực Generative Sandbox của v0-clone xứng đáng được Tuyển mộ làm Skill bổ trợ.',
        advantage: 'AGENT',
      }
    ],
    summaryVerdict: 'AGENT-02 Mobile UX Architect chiến thắng nhờ tuân thủ hoàn hảo quy chuẩn Mobile-First 430px và Kiến trúc hệ thống. Đề xuất tuyển mộ tính năng Live Sandbox của v0-clone làm Skill tăng cường.',
    hireRecommendation: {
      shouldHire: true,
      suggestedAction: 'IMPORT_AS_SKILL',
      hireTitle: 'Generative UI Instant Sandbox Skill',
      rationale: 'Bổ sung năng lực sinh layout nhanh cho AGENT-02 giúp tăng tốc độ prototyping lên 300%.',
    }
  },
  'langchain-ai/langgraph': {
    id: 'battle-02',
    repoFullName: 'langchain-ai/langgraph',
    repoName: 'langgraph',
    agentCode: 'AGENT-01',
    agentName: 'Lead Orchestrator',
    matchDate: '2026-09-01 15:48',
    winner: 'AGENT',
    scoreRepo: 91,
    scoreAgent: 95,
    criteriaScores: [
      {
        name: 'Architecture & Code Maturity',
        nameVi: 'Độ hoàn thiện & Kiến trúc Code',
        repoScore: 94,
        agentScore: 96,
        weight: 0.25,
        analysis: 'LangGraph có cấu trúc State Graph mạnh mẽ. AGENT-01 có kinh nghiệm điều phối 13 subagents thực tế.',
      },
      {
        name: 'Mobile-First 430px Parity',
        nameVi: 'Tối ưu Mobile-First & Responsive 430px',
        repoScore: 70,
        agentScore: 95,
        weight: 0.25,
        analysis: 'LangGraph chủ yếu xử lý backend graph; AGENT-01 điều phối cả pipeline visualizer trên mobile.',
      },
      {
        name: 'Security & RBAC Strictness',
        nameVi: 'Tuân thủ Bảo mật & Phân quyền RBAC',
        repoScore: 88,
        agentScore: 96,
        weight: 0.20,
        analysis: 'AGENT-01 tuân thủ nghiêm ngặt RBAC Guard trong toàn bộ chuỗi ủy thác task.',
      },
      {
        name: 'Performance & Latency',
        nameVi: 'Hiệu năng & Tốc độ thực thi',
        repoScore: 90,
        agentScore: 94,
        weight: 0.15,
        analysis: 'Cả hai bên duy trì độ trễ xử lý thấp < 300ms cho mỗi bước phân rã.',
      },
      {
        name: 'Squad Synergy & Integration Ease',
        nameVi: 'Độ tương thích & Khả năng phối hợp',
        repoScore: 96,
        agentScore: 95,
        weight: 0.15,
        analysis: 'Cực kỳ phù hợp để tích hợp MCP Tool State Graph cho Leader Agent.',
      }
    ],
    battleLog: [
      {
        round: 1,
        topic: 'Hiệp 1: Khả năng Phân rã Đa tác tử Phức tạp',
        commentary: 'LangGraph trình diễn State Graph đa nhánh xuất sắc. AGENT-01 đáp trả bằng khả năng điều phối 13 Agent chuyên biệt.',
        advantage: 'EQUAL',
      },
      {
        round: 2,
        topic: 'Hiệp 2: Xử lý Lỗi Tự Động & Checkpointing',
        commentary: 'LangGraph ghi điểm với cơ chế Time-travel Checkpoint mạnh mẽ.',
        advantage: 'REPO',
      },
      {
        round: 3,
        topic: 'Hiệp 3: Tích hợp Toàn diện với Vercel & Supabase',
        commentary: 'AGENT-01 chứng minh sự tương thích tuyệt đối với hạ tầng Cloud hiện hành.',
        advantage: 'AGENT',
      }
    ],
    summaryVerdict: 'AGENT-01 giữ vững vị thế đội trưởng. Tuyển mộ cơ chế Cyclic State Graph của LangGraph để nâng cấp độ bền vững của Squad.',
    hireRecommendation: {
      shouldHire: true,
      suggestedAction: 'INTEGRATE_MCP',
      hireTitle: 'LangGraph State Graph MCP Engine',
      rationale: 'Tích hợp Cyclic State Machine giúp Squad tự hồi phục khi gặp lỗi phức tạp.',
    }
  }
};

export const INITIAL_HIRED_PROPOSALS: HiredSkillProposal[] = [
  {
    id: 'prop-01',
    repoFullName: 'v0-community/v0-clone',
    skillName: 'Generative UI Instant Sandbox Skill',
    category: 'FRONTEND',
    assignedSquad: 'Frontend & UX Squad (AGENT-02 & AGENT-09)',
    status: 'APPROVED',
    rationale: 'Bổ sung công cụ Live Sandbox tạo nguyên mẫu giao diện nhanh gấp 3 lần cho Mobile UX Architect.',
    hiredBy: 'ADMIN_CEO',
    createdAt: '2026-09-01 15:46',
  },
  {
    id: 'prop-02',
    repoFullName: 'supermemoryai/supermemory',
    skillName: 'Persistent Context Memory Graph',
    category: 'OPTIMIZER',
    assignedSquad: 'Memory & Context Squad (AGENT-13)',
    status: 'INTEGRATED',
    rationale: 'Tăng cường dung lượng lưu trữ ngữ cảnh dài hạn và truy vấn vector đa chiều cho toàn bộ squad.',
    hiredBy: 'HEAD',
    createdAt: '2026-09-01 15:30',
  },
  {
    id: 'prop-03',
    repoFullName: 'deepseek-ai/deepseek-coder',
    skillName: 'Clean Code Uncle Bob Reasoning Evaluator',
    category: 'ARCHITECT',
    assignedSquad: 'Code Review Squad (AGENT-12)',
    status: 'PROPOSED',
    rationale: 'Tự động kiểm tra tiêu chuẩn Clean Code và phát hiện code smells trước khi commit.',
    hiredBy: 'DEV',
    createdAt: '2026-09-01 15:47',
  }
];

// Helper to generate dynamic solo battle result for any repo
export function generateSoloBattleResult(repo: GitHubTrendingRepo, agent: AgentRoleProfile): SoloBattleResult {
  const repoScore = Math.floor(Math.random() * 15) + 82;
  const agentScore = Math.floor(Math.random() * 10) + 90;
  const isAgentWinner = agentScore >= repoScore;

  return {
    id: `battle-${Date.now()}`,
    repoFullName: repo.fullName,
    repoName: repo.name,
    agentCode: agent.code,
    agentName: agent.name,
    matchDate: new Date().toISOString().replace('T', ' ').slice(0, 16),
    winner: isAgentWinner ? 'AGENT' : 'REPO',
    scoreRepo: repoScore,
    scoreAgent: agentScore,
    criteriaScores: [
      {
        name: 'Architecture & Code Maturity',
        nameVi: 'Độ hoàn thiện & Kiến trúc Code',
        repoScore: Math.floor(Math.random() * 15) + 80,
        agentScore: Math.floor(Math.random() * 10) + 90,
        weight: 0.25,
        analysis: `${agent.name} thể hiện sự vượt trội về cấu trúc phân lớp và quy chuẩn Clean Code trong Squad.`,
      },
      {
        name: 'Mobile-First 430px Parity',
        nameVi: 'Tối ưu Mobile-First & Responsive 430px',
        repoScore: Math.floor(Math.random() * 20) + 75,
        agentScore: Math.floor(Math.random() * 8) + 92,
        weight: 0.25,
        analysis: 'Kiểm thử thực tế trên viewport iPhone 14 Pro Max 430px cho thấy độ tương thích vượt trội.',
      },
      {
        name: 'Security & RBAC Strictness',
        nameVi: 'Tuân thủ Bảo mật & Phân quyền RBAC',
        repoScore: Math.floor(Math.random() * 18) + 78,
        agentScore: Math.floor(Math.random() * 6) + 94,
        weight: 0.20,
        analysis: 'Hệ thống Role-Based Guard của Squad thiết lập lớp phòng thủ nghiêm ngặt theo phân quyền CEO/HEAD.',
      },
      {
        name: 'Performance & Latency',
        nameVi: 'Hiệu năng & Tốc độ thực thi',
        repoScore: Math.floor(Math.random() * 10) + 88,
        agentScore: Math.floor(Math.random() * 8) + 92,
        weight: 0.15,
        analysis: 'Độ trễ trung bình < 250ms, đáp ứng chuẩn Vercel Edge Cloud.',
      },
      {
        name: 'Squad Synergy & Integration Ease',
        nameVi: 'Độ tương thích & Khả năng phối hợp',
        repoScore: Math.floor(Math.random() * 10) + 88,
        agentScore: Math.floor(Math.random() * 6) + 94,
        weight: 0.15,
        analysis: `Repo ${repo.name} mang lại giá trị gia tăng cao cho bộ kỹ năng của ${agent.code}.`,
      }
    ],
    battleLog: [
      {
        round: 1,
        topic: `Hiệp 1: So sánh Tiêu chuẩn Kỹ thuật & Kiến trúc Hệ thống (${repo.name} vs ${agent.code})`,
        commentary: `${agent.name} làm chủ hoàn toàn quy trình xử lý với 99%+ tỷ lệ thành công thực tế trong squad.`,
        advantage: 'AGENT',
      },
      {
        round: 2,
        topic: `Hiệp 2: Đánh giá Tính năng Chuyên biệt & Điểm mạnh của ${repo.name}`,
        commentary: `${repo.fullName} chứng minh sức mạnh với ${repo.stars.toLocaleString()} Stars trên cộng đồng GitHub.`,
        advantage: 'REPO',
      },
      {
        round: 3,
        topic: 'Hiệp 3: Tối ưu Hóa cho Thiết bị Di động (Mobile 430px & Touch UX)',
        commentary: 'Các nút bấm của Squad tuân thủ chặt chẽ token font 11.5px-12.5px, height 28px-38px.',
        advantage: 'AGENT',
      },
      {
        round: 4,
        topic: 'Hiệp 4: Phán quyết Chung cuộc & Quyết định Tuyển dụng',
        commentary: `Trận đấu khép lại với phần thắng nghiêng về ${agent.code} (${agentScore} vs ${repoScore}). Đề xuất nhập repo vào hệ thống Skill của Squad.`,
        advantage: 'AGENT',
      }
    ],
    summaryVerdict: `Trận so găng kết thúc xuất sắc. ${agent.name} thể hiện năng lực vững vàng. Đề xuất tuyển mộ ${repo.name} làm Skill mở rộng.`,
    hireRecommendation: {
      shouldHire: true,
      suggestedAction: repo.topics.includes('mcp') ? 'INTEGRATE_MCP' : 'IMPORT_AS_SKILL',
      hireTitle: `${repo.name.toUpperCase()} Augmented Capability Skill`,
      rationale: `Tích hợp năng lực từ ${repo.fullName} (${repo.stars.toLocaleString()} stars) giúp tối ưu năng suất làm việc của ${agent.code}.`,
    }
  };
}

// Realtime Event Helpers
export function emitRealtimeUpdate(eventName: string, data?: any) {
  if (typeof window !== 'undefined') {
    const event = new CustomEvent(eventName, { detail: data });
    window.dispatchEvent(event);
    try {
      localStorage.setItem('gcm_last_event', JSON.stringify({
        event: eventName,
        data,
        timestamp: Date.now()
      }));
    } catch (e) {
      console.warn('Storage sync error:', e);
    }
  }
}

export function subscribeRealtimeUpdate(eventName: string, handler: (e: CustomEvent) => void) {
  if (typeof window === 'undefined') return () => {};
  
  const listener = (event: Event) => {
    handler(event as CustomEvent);
  };
  
  window.addEventListener(eventName, listener);
  
  const storageListener = (e: StorageEvent) => {
    if (e.key === 'gcm_last_event' && e.newValue) {
      try {
        const payload = JSON.parse(e.newValue);
        if (payload.event === eventName) {
          handler(new CustomEvent(eventName, { detail: payload.data }));
        }
      } catch (err) {
        console.error('Failed to parse storage event:', err);
      }
    }
  };
  window.addEventListener('storage', storageListener);

  return () => {
    window.removeEventListener(eventName, listener);
    window.removeEventListener('storage', storageListener);
  };
}
